NeonGeckoCom/neon-utils

neon_utils/skills/neon_skill.py, version.py
Move skill configuration to `skill.file_system` to allow OSM updates and match OVOS/Mycroft convention
=> Move skill config location to skill.file_system

neon_utils/configuration_utils.py
Prevent `filelock` from spamming logs on config load
=> Suppress filelock logs

neon_utils/configuration_utils.py, neon_utils/default_configurations/default_core_conf.yml, tests/configuration_util_tests.py
Adds a method to write Neon Config to a mycroft-compatible .conf file (with unit test)
Includes bugfix for neon_core checks
Includes bugfix for language detection/translate modules
=> Config bugfixes and Mycroft/HolmesV compatibility

neon_utils/configuration_utils.py, tests/configuration_util_tests.py
Prevent overwriting config with empty "clean" config
Handle and test file permissions errors
=> Improved config error handling

neon_utils/configuration_utils.py
This puts configuration files in git cloned NeonCore directories, regardless of venv directory name
=> Relocate config files for git cloned installations

neon_utils/mq_utils.py, requirements.txt, tests/mq_util_tests.py
Makes get_mq_response manually ACK messages to prevent consuming messages intended for other clients
=> Fix get_mq_response message ACK

neon_utils/file_utils.py
Move soundfile import into `audio_bytes_to_file` for backwards compatibility when libsndfile is not available
=> Fix libsndfile import for backwards compatibility

neon_utils/configuration_utils.py, neon_utils/default_configurations/default_core_conf.yml
Add messagebus ssl params to config
Add sync_skill_settings to api config
Remove TTS/STT warnings when configured engines differ from defaults
=> Update default config and logged warnings

neon_utils/configuration_utils.py
Supports dev environments where packages are cloned locally and installed to a common environment with the --editable flag
Example Directory Structure:
Neon
|- NeonCore
|- neon_audio
|- neon_enclosure
|- neon_speech
|- venv
=> Add editable installation path to get_config_dir()

neon_utils/configuration_utils.py, tests/configuration/local_conf_no_language.yml, tests/configuration_util_tests.py
Move translation/detection module spec to 'language' in local config
Add boost, core_lang, and libretranslate default config values
Handle moving config from stt to language with unit tests
=> Add core 'language' settings

neon_utils/configuration_utils.py
Add `_loaded` key to auth_config to prevent attempted regeneration of file from missing key files
=> Fix prevent attempted regen of auth config

neon_utils/ccl_utils.py, neon_utils/service_apis/__init__.py
#203 Introduced the new method but did not update calls. Objective is to phase out support for `get_mq_response` and use the new `send_mq_request` method that has a different signature to make responses optional
=> Refactor MQ calls from `get_mq_response` to `send_mq_request`

neon_utils/skills/mycroft_skill.py
Move wait in get_response to handle text before (or right after) TTS is completed
=> get_response skip wait for playback completion

neon_utils/skills/mycroft_skill.py
Use `dict` instead of `deepcopy` in `_init_settings` for ovos-core compat fix
=> ovos-core skill settings compatibility patch

neon_utils/packaging_utils.py, neon_utils/skills/neon_skill.py
Fix `voc_match` handling of resources in neon_core
Fix path returned by `get_neon_core_root` in some cases
=> Core integration bugfixes

neon_utils/validator_utils.py
Unable to reliably reproduce for troubleshooting, but this import error is consistently raised when loading device-control-center.
This quick fix patches the issue but doesn't address the root cause which should be addressed in lingua_nostra or neon_core directly
=> Patch lingua_nostra import errors

neon_utils/configuration_utils.py, neon_utils/skills/neon_skill.py, tests/configuration_util_tests.py
In Docker implementations, default config/cache paths are not guaranteed to exist; adds conditional creation of directories in config/skills
=> Ensure config and cache directories exist

neon_utils/configuration_utils.py
Better handling of default path
Improved logging and docstrings warning file overwrites
Prevent writing unchanged config for minor efficiency
=> Minor changes to `write_mycroft_compatible_config`

neon_utils/message_utils.py, tests/message_util_tests.py
If the decorated method has an unfilled `message` param, this decorator uses `dig_for_message` to fill the parameter
=> Add resolve_message decorator with unit tests

neon_utils/configuration_utils.py, tests/configuration/unwritable_path/ngi_local_conf.yml, tests/configuration_util_tests.py
Updates `init_config_dir` to handle migration of old-style yml config to new `neon.yaml` spec
Should resolve issue with Kubernetes containers running with old config
=> Legacy Config Migration

neon_utils/configuration_utils.py, tests/configuration/neon_core/configuration/neon.yaml, tests/configuration_util_tests.py
Patches bug introduced in #366 
Adds unit test case for modified default config directory
These changes also mean calls to `init_config_dir` after a reference to `ovos_config` will force reloading of loaded Configuration
=> Force recreation of Configuration object after building ovos.conf

neon_utils/skills/mycroft_skill.py, tests/neon_skill_tests.py
Make `get_response` speak events private on Klat since replies are only handled for original user anyway
Skip `wait` handling in `speak` for Klat since this has no meaning in server implementations Add unit test that private messages are handled in `get_response`
=> Fix get_response Klat handling

neon_utils/log_utils.py, neon_utils/logger.py, tests/license_tests.py, tests/log_util_tests.py
Adds method to initialize `LOG` singleton. Mostly duplicates init that normally happens [in ovos-core](https://github.com/OpenVoiceOS/ovos-core/blob/dev/mycroft/__init__.py)
=> Fix log settings init

neon_utils/configuration_utils.py, neon_utils/default_configurations/default_user_conf.yml, neon_utils/skills/mycroft_skill.py, tests/configuration_util_tests.py
Update `mycroft_compatible_location` method to fall back to default core config if user location isn't specified. Also adds unit tests for incomplete location configs
=> Remove default user location config

neon_utils/skills/mycroft_skill.py, tests/neon_skill_tests.py
Problem: the validator as is returns the response. This is cumbersome, because sometimes you have to do things twice.
As a simple example, you want to ensure a datetime from a response you have to extract it once in the validator and the second time in the calling function to get the datetime.
This addition will optionally return the validated value if not `True` is returned from the validator (if `True` the original response; backwards compat)
If the validated value is `False` or `None` it depends on `num_retries` how to proceed. (if to ask again or return None)
=> Get response from validated value

neon_utils/skills/mycroft_skill.py, tests/neon_skill_tests.py
Update `get_response` to better support event-based speaking checks
Goes with https://github.com/NeonGeckoCom/neon_audio/pull/91
=> Add support for event-based `wait_while_speaking`

neon_utils/skills/__init__.py, neon_utils/skills/neon_skill.py, tests/neon_skill_tests.py, tests/skills/__init__.py
Adds a `chat_handler` decorator to expose a specific method via a messagebus event. An incoming message is treated as an utterance, so this may be used on a regular intent handler
i.e.:
```python
@chat_handler('wolfram')
def handle_chat_message(message: Message):
utterance = message.data.get('utterance')
self.speak('response')
```
A request would look like: `Message("chat.wolfram", {"utterance": "hello"}, {})
=> Add `chat_handler` decorator with bus registration

neon_utils/mq_utils.py, requirements/network.txt, requirements/requirements.txt
Move MQ Connector dependency to `network` extra to troubleshoot circular dependency bugs in version resolution
=> Make MQ dependencies network optional extras

setup.py
Fix setup.py to use file-relative paths instead of cwd-relative paths
Fixes bug discovered in #414 
Relates to https://github.com/NeonGeckoCom/.github/pull/6
=> Fix relative path references in setup.py

neon_utils/skills/mycroft_skill.py
Remove `secondary_langs` property override since this is core-oriented and not user-oriented for skills
Resolves [skill failures](https://github.com/NeonGeckoCom/skill-about/actions/runs/4265209510/jobs/7424271263)
There is a user-oriented secondary language config, but it is not relevant here, only for STT. For skills, supported/secondary languages are determined by the skill
=> Update `secondary_langs` skill property

requirements/audio.txt
librosa 0.10 added `soxr`, an LGPL licensed dependency. This pins a max librosa version to avoid dragging this incompatible license.
=> Pin max librosa version to avoid LGPL dependency

neon_utils/parse_utils.py, tests/parse_util_tests.py
Adds `parse_utils.validate_email` to check for a valid email address and do minimal parsing to make the passed string valid.
=> Add email validation util

README.md, neon_utils/location_utils.py, tests/location_util_tests.py
Reformat location_utils for editor warnings
Make sure Nominatim user-agent is consistent
Add 'village' handling like https://github.com/NeonGeckoCom/skill-user_settings/pull/69
Use an alternate Nominatim host
Continuation of fix from #436
=> More Nominatim fixes

neon_utils/configuration_utils.py
Ensure config directory is initialized when writing config from legacy setup script
=> Add call to `init_config_dir` in legacy setup config handling

neon_utils/skills/common_play_skill.py, neon_utils/skills/neon_skill.py, neon_utils/validator_utils.py, requirements/test_requirements.txt, tests/skills/__init__.py
Refactor package to import from ovos-workshop and ovos-utils to remove `mycrfot` imports
Relates to #469 
`ovos-core` is still listed as a test dependency as some tests are failing without it. Failures appear to be related to configuration handling, but are not immediately resolvable so this will be left to a future PR, possibly after some of the configuration marked for deprecation is actually deprecated
=> Remove ovos core dependency

neon_utils/skills/common_play_skill.py, neon_utils/skills/common_query_skill.py, neon_utils/skills/neon_fallback_skill.py, tests/neon_skill_tests.py, tests/signal_util_tests.py
Troubleshoot FallbackSkill inheritance
Update CommonQuerySkill to extend ovos_workshop implementation
Mark CommonPlaySkill as deprecated
=> Update Skill base classes

neon_utils/skills/common_query_skill.py, neon_utils/skills/neon_fallback_skill.py, requirements/test_requirements.txt, tests/neon_skill_tests.py
Troubleshooting ovos-workshop skills compat. with 0.0.12 and 0.0.13aX
Continuation of #478
=> Troubleshooting Skill Class Init

neon_utils/metrics_utils.py
Depending on init order, importing `Stopwatch` from `neon_utils.metrics_utils` could cause an import error depending on where `Stopwatch` was being used
=> Fix extra metrics utils import

neon_utils/skills/neon_skill.py
Temporarily patches `add_event` to prevent multiple listeners for the same skill
Proper fix: https://github.com/OpenVoiceOS/OVOS-workshop/pull/148
Temporarily patching for immediate NeonOS update and in case a NeonCore stable release is needed before a stable ovos-workshop
=> Patch multiple native languages intent registration

neon_utils/metrics_utils.py
Fix bug initialization in metrics reporting
Add generic exception handling to prevent exceptions on `stopwatch` exit
Follow-up to #485
=> Fix bug in default metrics bus handling

neon_utils/user_utils.py, tests/user_util_tests.py
Handle malformed `user_profiles` Message context with fallback to default user config
Relates to issue with Time skill seen in https://github.com/NeonGeckoCom/neon-iris/pull/51
=> Better default profile handling

neon_utils/location_utils.py
As of 12/25, maps.co now [requires API keys](https://geocode.maps.co/) which are not easily added to geopy. Longer-term, I think geolocation should be added to `neon-api-proxy` as other paid/metered services are but the API change has broken stable releases without warning
=> Use OpenStreetMap geocoder to work around maps.co API changes

neon_utils/skills/mycroft_skill.py, neon_utils/skills/neon_skill.py, requirements/requirements.txt
Update ovos-workshop dependency
Resolve and patch deprecation warnings
=> Update for ovos-workshop compat

.github/workflows/unit_tests.yml, neon_utils/hana_utils.py, tests/hana_util_tests.py
Add `hana_utils` with unit tests
Eventually, Hana should be integrated with `ovos-backend-client` but until then this will not assume any Configuration changes as it should ideally use `server ` config which is parsed by `ovos-backend-client`. For the moment, the module has a valid hard-coded server reference and accepts a URL argument so callers may choose how to specify a server address
=> Add utilities for interfacing with Neon HANA

neon_utils/hana_utils.py
Ensure config directory exists before writing to it in `hana_utils`
Introduced in #497
=> Fix directory errors in hana_utils

neon_utils/skills/neon_fallback_skill.py
Refactor neon_fallback_skill.py to prevent import errors when `network` extras aren't installed
Failure noted https://github.com/NeonGeckoCom/skill-caffeinewiz/actions/runs/8117513197/job/22189842281
=> Resovle optional dependency import error in skills module

neon_utils/message_utils.py
It is now up to the MQ client to determine if a message should be sent to Neon and all messages expect responses
=> Mark `neon_must_respond` method as deprecated

neon_utils/skills/common_query_skill.py
Add forwards-compat with ovos-core 0.0.8 CommonQuery
Mark CommonQuerySkill as deprecated
Relates to https://github.com/NeonGeckoCom/NeonCore/pull/641
=> Add ovos-core 0.0.8 compat. for CommonQuery skills

neon_utils/skills/common_play_skill.py, neon_utils/skills/neon_skill.py
Pulls in the old `save_settings()` function that was removed in ovos-utils 0.1.0
Deletes the import for save_settings and also for get_local_settings, which wasn't actually being used anyway.
N/A
This should be backwards-compatible, since one import was unused and the other is now no longer dependent on an external package.
=> slight refactor for ovos-utils 0.1.0

neon_utils/skills/neon_fallback_skill.py
Add `NeonSkill` import for backwards-compat
Resolves import error in LLM fallback skill https://github.com/NeonGeckoCom/skill-fallback_llm/blob/94f2d5613076bc827f57a01d96c2d3c74ac1dea6/__init__.py#L38
=> Add backwards-compat import to `neon_fallback_skill` module

neon_utils/hana_utils.py, tests/hana_util_tests.py
Update to read default `hana` backend URL from configuration
=> Enable `hana` backend URL to be configured

neon_utils/skills/neon_skill.py
Deprecate patched `add_event` method for latest ovos-workshop compat.
Needed for https://github.com/NeonGeckoCom/NeonCore/pull/641
=> Remove old patch

neon_utils/skills/neon_fallback_skill.py, neon_utils/skills/neon_skill.py, tests/web_util_tests.py
Replace deprecated import
Includes unit test updates to account for new neon.ai website
Missed in #515
=> Update deprecated import to supported path

neon_utils/hana_utils.py, neon_utils/mq_utils.py, neon_utils/skills/kiosk_skill.py, neon_utils/skills/neon_fallback_skill.py, requirements/requirements.txt, tests/neon_skill_tests.py, tests/net_util_tests.py
Removes deprecated patch
Updates hard-coded URLs to maintained references
Adds retry logic to work around occasional HANA errors
- Troubleshooting https://github.com/NeonGeckoCom/neon-utils/actions/runs/9311476602/job/25630698401?pr=527
- Needs https://github.com/OpenVoiceOS/OVOS-workshop/pull/207
=> Resolve Test Failures

neon_utils/location_utils.py, requirements/requirements.txt, tests/location_util_tests.py
Refactor location_utils to use `pytz` instead of `pendulum`
Relates to https://github.com/NeonGeckoCom/pyklatchat/pull/96
Unrelated test failures fixed by https://github.com/NeonGeckoCom/neon-utils/pull/528
`pytz` is already used in `skill-date_time` among other places, so this removes a dependency in most distributions.
=> Refactor to use pytz instead of pendulum

neon_utils/hana_utils.py, tests/hana_util_tests.py
Pad expired tokens by 30s to renew before expiration
Handle expired token responses by renewing token and re-requesting backend
=> Mitigate issues with expired HANA tokens

neon_utils/hana_utils.py
Fixes issue where headers would continue to include an old token after a refresh
Also refactors token cache filename to include human-readable URL
Continues #529 
Closes https://github.com/NeonGeckoCom/skill-support_helper/issues/79
Closes https://github.com/NeonGeckoCom/skill-weather/issues/56
=> Fix bug causing old token to be used with requests after refreshing

.github/workflows/unit_tests.yml, neon_utils/configuration_utils.py, requirements/requirements.txt, tests/configuration_util_tests.py
Update ovos package dependency specs to allow 0.1+ versions
Mark `init_config_dir` as deprecated
Relates to https://github.com/NeonGeckoCom/NeonCore/pull/708
=> Enable dependency resolution of latest ovos packages

neon_utils/skills/mycroft_skill.py
Duplicates imported method deprecated in ovos-utils
Replaces #525
Failure noted in https://github.com/NeonGeckoCom/skill-date_time/actions/runs/10852700501/job/30119334006
All usage of this is already marked as deprecated; this is just a patch until neon-utils 2.0.0 fully deprecates the affected code
=> Patch backwards-compat method removed from ovos-utils 0.1

neon_utils/log_aggregators/__init__.py, neon_utils/log_aggregators/sentry.py, requirements/sentry.txt, setup.py
Added support for initializing Sentry along with general support for log aggregators integration
=> Integration with Sentry

.github/workflows/unit_tests.yml, tests/hana_util_tests.py
Update tests to remove Python 3.7 and add 3.11-3.12
Updates hana tests to account for backend fix: https://github.com/NeonGeckoCom/neon-hana/pull/35
Test failures related to deprecation noted in https://github.com/NeonGeckoCom/neon-utils/pull/539
=> Update Python versions in tests

.github/workflows/unit_tests.yml
Update Python versions in unit tests to remove 3.8 and add 3.12
Update shared actions to latest versions
Add `setuptools` installation to test automation for Python3.12 support
Closes #542
=> Update unit test automation for Python 3.12 support

neon_utils/metrics_utils.py
Refactor `neon_utils.mq_utils` import to import from defining module
Resolves logged deprecation warnings on Mark2
=> Refactor deprecated import

neon_utils/process_utils.py
Implements a helper method to start an HTTP server with a `/status` endpoint based on ProcessState
Helper method includes a `status_callback` kwarg which allows for specifying a method to be called before reporting service status (i.e. to perform additional checks that may change service status)
=> Add helper to start a health check server

neon_utils/process_utils.py
Override `/status` server endpoint logging to use configured `LOG` object
Prevents logging all status requests to stderr
Follow-up to #551
=> Override `/status` server endpoint logging
