NeonGeckoCom/neon-utils

neon_utils/web_utils.py

Reorg strip_tags-related class into function
Simplify and normalize scrape_page_for_links

Fix web_utils unit testing failures

---

.github/workflows/pull_master.yml
LICENSE.md
README.md
neon_utils/__init__.py
neon_utils/logger.py
neon_utils/skill_override_functions.py
neon_utils/web_utils.py
setup.py
version.py

Add LICENSE.md
Refactor Copyright notice in file headers

Prep for release

---

neon_utils/__init__.py
requirements.txt
tests/skill_patch_tests.py
version.py

Add ovos utils requirement
Use ovos utils to check for local gui availability

GUI support

---

neon_utils/parse_utils.py
tests/parse_util_tests.py
tests/skill_patch_tests.py
tests/test_objects.py
tests/web_util_tests.py

Add parse_util_tests.py
Update license notices

Testing and license updates

---

.github/workflows/unit_tests.yml
neon_utils/net_utils.py
neon_utils/transcript_utils.py
neon_utils/web_utils.py
tests/net_util_tests.py
tests/transcript_util_tests.py

Feat add net utils

---

neon_utils/configuration_utils.py
neon_utils/default_configurations/default_core_conf.yml
neon_utils/language_utils.py
neon_utils/skills/neon_skill.py
tests/configuration_util_tests.py
tests/language_util_tests.py
version.py

Replace to-be-depreciated keys
Improved config testing
Added config convenience methods
Improved config reload to ensure references are up-to-date

Update for Neon Core backwards compatibility

---

neon_utils/configuration_utils.py
neon_utils/default_configurations/default_core_conf.yml
tests/configuration_util_tests.py
version.py

Update config updates to handle standard depth=2
Add missing config keys

Config updates and bugfixes

---

neon_utils/configuration_utils.py
neon_utils/language_utils.py
tests/language_util_tests.py

Remove false warning log
Fix typo in save_utterances preference lookup
Add confirm_listening preference to speech config

Fix bugs in speech config

---

.github/workflows/unit_tests.yml
neon_utils/log_utils.py
neon_utils/skills/neon_skill.py
tests/log_util_tests.py
version.py

Add log utils to cycle logfiles, create loggers, get logfile paths

Add log utils

---

.github/workflows/unit_tests.yml
neon_utils/metrics_utils.py
tests/metric_util_tests.py

Provides a drop-in replacement of mycroft.metrics Stopwatch for more general availability in external packages

Add stopwatch with unit tests

---

neon_utils/authentication_utils.py
neon_utils/configuration_utils.py
neon_utils/default_configurations/default_core_conf.yml
tests/authentication_util_tests.py
tests/configuration_util_tests.py
version.py

Update get_skill_config for NeonCore compat.
More complete skill config unit tests
Add method to check if repo is Neon authenticated for Neon Skills module support

NeonCore skills module compat

---

neon_utils/skills/neon_skill.py

Update voc_match to locate vocab files in neon_core if not found in skill or user directories

Handle voc_match resources in packaged installations

---

neon_utils/authentication_utils.py
neon_utils/configuration_utils.py
neon_utils/default_configurations/default_core_conf.yml
setup.py
tests/configuration_util_tests.py

Import config from environment variables set during installation

Handle config import at setup

---

neon_utils/parse_utils.py
tests/parse_util_tests.py
version.py

Added safety checks in parse_utils
Added util to normalize strings for TTS

Updated parse utils

---

neon_utils/authentication_utils.py
neon_utils/configuration_utils.py
tests/authentication_util_tests.py
tests/configuration_util_tests.py
tests/credentials/alpha_vantage.txt
tests/credentials/owm.txt

Add methods to locate API key files
Export API keys to config file
Unit tests

Locate and export keys to ngi_auth_vars

---

.github/workflows/unit_tests.yml
neon_utils/authentication_utils.py
neon_utils/service_apis/__init__.py
neon_utils/service_apis/alpha_vantage.py
neon_utils/service_apis/financial_modeling_prep.py
neon_utils/service_apis/open_weather_map.py
neon_utils/service_apis/wolfram_alpha.py
requirements.txt
tests/service_api_tests.py

Add service_apis module
Fix bug in build_new_auth_config default location
Wrap calls to APIs to forward to Neon API server when credentials not provided
Add service api tests to automation

Add service_api module to isolate API access

---

neon_utils/skills/neon_skill.py

Update `self.configuration_available` refs to `self.local_config`

Remove depreciated references in NeonSkill class

---

neon_utils/message_utils.py
tests/message_util_tests.py

Add message utils to encode/decode bytes to strings for passing byte data in message objects

Byte encode/decode methods

---

.github/workflows/unit_tests.yml
neon_utils/socket_utils.py
tests/socket_utils_tests.py

Added utils for handling socket communication. Adding of this module should make it clear on how modules utilizing tcp sockets should communicate.

Socket Utils

---

.github/workflows/publish_release.yml
.github/workflows/publish_test_build.yml
.gitignore
setup.py
version.py
version_bump.py

Adds automated alpha version changes on pushes to the `dev` branch
Adds automated release creation on pushes to the `master` branch
Pushes Alpha versions to PyPI on pushes to `dev`, and new versions on pushes to `master`

PyPI and Github release automation

---

.github/workflows/unit_tests.yml
neon_utils/configuration_utils.py
neon_utils/skills/neon_skill.py
tests/configuration_util_tests.py
tests/neon_skill_tests.py
tests/search_util_tests.py
tests/service_api_tests.py
tests/skill_patch_tests.py
tests/skills/__init__.py
tests/skills/test_objects.py
version.py

Update skill config references to use methods instead of direct file references
Cleanup skill settings init
Consolidate all skill settings files to one location (Mycroft standard)
Add skill object tests

Update skill class and unit tests

---

neon_utils/configuration_utils.py

Check for skillRepo environment variable and populate default_skills on setup

Add support for default_skills to be defined during setup

---

neon_utils/configuration_utils.py
neon_utils/default_configurations/default_core_conf.yml
neon_utils/skills/__init__.py
neon_utils/skills/mycroft_skill.py
neon_utils/skills/neon_skill.py
tests/configuration/skill_settingsmeta.json
tests/configuration_util_tests.py
tests/neon_skill_tests.py
tests/skills/__init__.py

Patch MycroftSkill class to handle skills settings save location and default load

Patch Skills Settings

---

neon_utils/service_apis/__init__.py
neon_utils/service_apis/alpha_vantage.py
neon_utils/service_apis/open_weather_map.py
tests/service_api_tests.py

Add get_current_weather API method with unit test
Add unit test for unimplemented remote API
Catch error return cases from Neon API

Update Neon API unit tests and add current weather method

---

neon_utils/configuration_utils.py
tests/configuration_util_tests.py

Handle devType environment var in `create_config_from_setup_params`

Handle devType in Pi setup

---

.github/workflows/unit_tests.yml
neon_utils/mq_utils.py
neon_utils/service_apis/__init__.py
requirements.txt
tests/mq_util_tests.py
tests/service_api_tests.py

Refactors MQ emit/response into `get_mq_response`
Added MQ utils unit tests
Handle known bug in wolfram API testing

Refactor MQ handling to generic method

---

neon_utils/mq_utils.py
neon_utils/service_apis/open_weather_map.py

Suppress pika debug logging
Handle outdated OWM returns

Logging and API Return processing

---

.github/workflows/unit_tests.yml
neon_utils/configuration_utils.py
neon_utils/skills/mycroft_skill.py
tests/neon_skill_tests.py

Update skill config to prevent creating empty paths
Prevent detecting system packages for config paths

Skill config and config path changes

---

neon_utils/file_utils.py

Move librosa import into `audio_bytes_from_file` method and log more useful error on exception

Fix librosa import errors

---

tests/cache_util_tests.py

Add tearDown to reset cache after each test
Refactor test_get to troubleshoot test failures
Closes #148

Resolve occasional CacheUtil test failures

---

neon_utils/net_utils.py
tests/net_util_tests.py

Updated unit tests to mock offline state in tests

Add check_online and check_url_response methods for online checks

---

.github/workflows/unit_tests.yml
neon_utils/lock_utils.py
requirements/requirements.txt
tests/lock_util_tests.py

Add lock utils inspired by https://github.com/forslund/combo-lock and forked to address https://github.com/forslund/combo-lock/issues/7

Add lock_utils with basic tests and added GH automation

---

neon_utils/configuration_utils.py
requirements/requirements.txt
tests/configuration/depreciated_language_config/.ngi_local_conf.tmp
tests/configuration/depreciated_language_config/.ngi_user_info.tmp
tests/configuration/depreciated_language_config/ngi_local_conf.yml
tests/configuration/depreciated_language_config/ngi_user_info.yml
tests/configuration_util_tests.py

Closes #180 
Adds support for `NEON_CONFIG_PATH` env var
Adds testing of known migration failure case (resolved)

Fix config migration bugs, support ENV config path

---

neon_utils/configuration_utils.py
neon_utils/logger.py
neon_utils/skills/neon_skill.py

Suppress filelock and botocore debug logs in logger.py
Reorg imports in neon_skill.py

Cleanup logging

---

.github/workflows/unit_tests.yml
requirements/requirements.txt
requirements/test_requirements.txt

Update unit_tests workflow to remove hard-coded HolmesV installs
Add HolmesV to test requirements
Add lingua_nostra to requirements

Cleanup dependencies

---

neon_utils/metrics_utils.py
neon_utils/mq_utils.py
tests/configuration/ngi_local_conf.yml
tests/metric_util_tests.py

Add mq util to send request without expecting a response
Add metrics reporting and connection announcement methods

Add MQ Metrics Reporting and update MQ Utils

---

.github/workflows/unit_tests.yml
neon_utils/signal_utils.py
neon_utils/skill_override_functions.py
tests/neon_skill_tests.py
tests/signal_util_tests.py

Add signal_utils with auto-determination of event manager vs files and unit tests

Signal Manager Support

---

neon_utils/configuration_utils.py
tests/configuration_util_tests.py

Add some annotations to other config modules

Add util to get config for GUI module with unit test

---

neon_utils/default_configurations/default_core_conf.yml
neon_utils/signal_utils.py
tests/signal_util_tests.py

Make signal max wait configurable
Add config param to spec create signal files

Add config params for signals

---

.github/workflows/unit_tests.yml
neon_utils/skill_override_functions.py
tests/deprecated_compat_tests.py

Fix signal method return values in skill_override_functions.py
Add test suite for deprecated method backwards-compat.

Fix Signal Method backwards-compat

---

neon_utils/skill_override_functions.py

Replace IPC_DIR for Core compat.

---

neon_utils/log_utils.py
tests/log_util_tests.py

Add `init_log_for_module` method to initialize a log file for the specified module

Add util to init module log file

---

.github/workflows/unit_tests.yml
neon_utils/configuration_utils.py
neon_utils/default_configurations/default_core_conf.yml
neon_utils/file_utils.py
tests/configuration/unwritable_path/ngi_auth_vars.yml
tests/configuration_util_tests.py
tests/file_util_tests.py

Update default skills.repo_url param
Add file_utils to check path permissions
Move `create_file` from configuration to file utils
Added permissions checks in configuration_utils
Reorg and update configuration and file unit tests
Handle loading config from RO directory

Add File Permissions utils and Update Configuration Handling

---

neon_utils/configuration_utils.py
tests/configuration/populate_tests/test_ro_dir/ngi_local_conf.yml
tests/configuration_util_tests.py

Fix relative path handling in _populate_read_only_config with unit test

Fix config path handling

---

neon_utils/configuration_utils.py
neon_utils/default_configurations/default_core_conf.yml
neon_utils/location_utils.py
tests/configuration_util_tests.py
tests/location_util_tests.py

Adds missing config overrides where Neon config has equivalent keys
Adds location config translation method with unit test

Increased Mycroft config compatibility and Added `get_full_location`

---

neon_utils/mq_utils.py

Close MQ Channel after response is received to close the connection in a thread-safe manner

mq_utils shutdown bugfix

---

neon_utils/file_utils.py
tests/commented_files/test_commented_file.txt
tests/file_util_tests.py

Add `load_commented_file` method to load commented files with unit tests

Add load_commented_file

---

neon_utils/configuration_utils.py
tests/configuration_util_tests.py

Add checks for quoted lat/lng in `get_mycroft_compatible_location` with updated unit tests

Fix location parsing bug

---

neon_utils/configuration_utils.py
neon_utils/parse_utils.py
tests/configuration_util_tests.py
tests/parse_util_tests.py

Fix single quote stripping in clean_quotes and refactor for optimization and readability
Add unit test for discovered config failure case

Quoted config location fixes

---

neon_utils/configuration_utils.py
neon_utils/location_utils.py

Catch exceptions getting location from nominatim
Remove country code determination in `get_mycroft_compatible_location`

Resolve logged errors getting location updates

---

neon_utils/packaging_utils.py
tests/packaging_util_tests.py

Update incorrect function docstring

Handle optional extras in `get_package_dependencies`

---

neon_utils/skills/mycroft_skill.py
neon_utils/skills/neon_skill.py
tests/neon_skill_tests.py

Remove deprecated methods/properties from skill objects

---

.github/workflows/unit_tests.yml
neon_utils/configuration_utils.py
tests/configuration_util_tests.py

**NOTICE** This removes Python 3.6 compatibility

Fix config init module reloading

---

neon_utils/authentication_utils.py
tests/authentication_util_tests.py

Deprecate methods for reading key files into deprecated Neon configuration
Reformat auth utils and tests for PEP

Deprecate unused auth_utils functions

---

neon_utils/skills/mycroft_skill.py
requirements/requirements.txt
tests/neon_skill_tests.py

Updates 'speak' message context to properly specify source/destination modules

Fix Speak Message source/destination contexts

---

.github/workflows/unit_tests.yml
neon_utils/configuration_utils.py
neon_utils/skills/mycroft_skill.py
requirements/configuration.txt
requirements/requirements.txt
setup.py

Move legacy ruamel.yaml dependency to `configuration` extra

---

.github/workflows/unit_tests.yml
neon_utils/user_utils.py
tests/user_util_tests.py

Add missing user_utils_tests run in unit_tests automation
Fix bug in user_utils profile updates overwriting context with default profile values
Update docstring to match behavior

User utils bugfix and unit test automation

---

neon_utils/configuration_utils.py
tests/configuration_util_tests.py

Includes system ovos_config files so containers/images with those configurations aren't overridden to use user config files

Update config handling to support global ovos.conf

---

neon_utils/configuration_utils.py

Skip forced reload of config modules if meta-config is unchanged during init

Clean up config init

---

neon_utils/net_utils.py
tests/net_util_tests.py

Update net_utils test case to new valid one
Update `check_port_is_open` to timeout

Resolve net_utils unit test failures

---

neon_utils/configuration_utils.py

Handle config reload on file relocation

---

neon_utils/skills/mycroft_skill.py
tests/neon_skill_tests.py
tests/skills/__init__.py

Update `PatchedMycroftSkill` init to be more readable

Add fallback skill init test

---

neon_utils/skills/skill_gui.py

Troubleshooting test failure https://github.com/NeonGeckoCom/skill-fallback_unknown/actions/runs/3752162643/jobs/6374002963

Troubleshoot ovos-core gui file resolution

---

neon_utils/skills/__init__.py
neon_utils/skills/neon_skill.py

Mark added chat_handler method as internal
Annotate future refactoring of `chat_handler` decorator to implement SkillAPI

`chat_handler` cleanup to prep release

---

neon_utils/skills/mycroft_skill.py
tests/neon_skill_tests.py

Add unit tests for `get_response` retries

Bugfixes in `get_response` retry

---

.github/workflows/license_tests.yml
.github/workflows/publish_release.yml
.github/workflows/publish_test_build.yml
.github/workflows/pull_master.yml
.github/workflows/unit_tests.yml

Update automation to shared repository
Add license test automation

Update GitHub Workflows

---

.github/workflows/publish_test_build.yml

Update build automation to default branch

---

.github/workflows/license_tests.yml
requirements/audio.txt

Include all possible dependencies in license tests
Exclude librosa version that includes LGPL dependencies
https://github.com/NeonGeckoCom/neon_speech/actions/runs/4248557504/jobs/7387858800

Remove LGPL dependency and Update Tests

---

requirements/requirements.txt

https://github.com/NeonGeckoCom/NeonCore/pull/372
https://github.com/NeonGeckoCom/NeonCore/pull/371

Resolve ovos-config compat bugs

---

.github/workflows/unit_tests.yml
neon_utils/configuration_utils.py
requirements/requirements.txt
tests/configuration_util_tests.py
tests/neon_skill_tests.py
tests/user_util_tests.py

Troubleshooting ovos-utils 0.0.29 compat.
Needs https://github.com/OpenVoiceOS/ovos-config/pull/30

ovos-config compat. fixes

---

requirements/requirements.txt

Spec stable dependencies to prep for release

Update ovos dependencies to stable versions

---

neon_utils/location_utils.py
tests/location_util_tests.py
tests/user_util_tests.py

Cleanup test changes patching a bug in ovos-utils
Includes fixes to new location util test failures

Revert extra config patching in unit tests

---

neon_utils/configuration_utils.py

Handle missing lat/lng config
https://github.com/NeonGeckoCom/skill-alerts/actions/runs/4411644551/jobs/7730358107

Handle null lat/lng from Neon user config

---

neon_utils/configuration_utils.py
tests/user_util_tests.py

Fix config handling to always include default location with unit tests
Fixes bug introduced in #424

Ensure default location config with unit test

---

.github/workflows/propose_release.yml
.github/workflows/publish_test_build.yml

Implement changelog automation and pre-release publishing

Implement Changelog Automation

---

.github/workflows/license_tests.yml
neon_utils/packaging_utils.py
neon_utils/skills/neon_skill.py

Update core package version checks and annotate deprecation
Update logging
Update license test automation

Update core version checks and annotate deprecation

---

neon_utils/parse_utils.py

Fix input value checks to prevent raising `ValueError`s for empty strings vs `None` types

Better argument validation in `parse_utils`

---

neon_utils/skills/common_message_skill.py
neon_utils/skills/common_play_skill.py
neon_utils/skills/common_query_skill.py
neon_utils/skills/instructor_skill.py
neon_utils/skills/mycroft_skill.py
neon_utils/skills/neon_skill.py

Pass kwargs in skill init for compat with newer ovos_workshop

Update Skill classes to support arbitrary kwargs passed at init

---

neon_utils/process_utils.py

Adds utils to trace and log memory usage with malloc

Add utilities to trace memory allocation

---

neon_utils/process_utils.py

Add handling of `debugging` configuration with periodic logging of memory use if enabled

Add periodic malloc logging based on configuration

---

requirements/requirements.txt

Update Pyyaml dependency to allow 6.0

---

neon_utils/configuration_utils.py
requirements/requirements.txt
tests/packaging_util_tests.py

Refactor `_init_ovos_conf` to use function from `ovos-config`
https://github.com/OpenVoiceOS/ovos-config/pull/42

Move config init to ovos-config

---

neon_utils/skills/neon_fallback_skill.py
requirements/requirements.txt
tests/web_util_tests.py

Init `FallbackSkill` for compat. with changes in latest ovos-workshop

Add call to init `FallbackSkill` from `ovos_workshop`

---

neon_utils/process_utils.py

Remove backwards-compat. config handling to prep for release

Remove backwards-compat. `debug` config handling

---

neon_utils/language_utils.py
neon_utils/message_utils.py
neon_utils/messagebus_utils.py
neon_utils/signal_utils.py
neon_utils/skills/common_play_skill.py
neon_utils/skills/kiosk_skill.py
neon_utils/skills/mycroft_skill.py
neon_utils/skills/neon_skill.py
neon_utils/user_utils.py
requirements/requirements.txt
tests/messagebus_util_tests.py
tests/signal_util_tests.py
tests/skills/__init__.py
tests/user_util_tests.py

Replace `mycroft-bus-client` with `ovos-bus-client`

Refactor messagebus client package

---

neon_utils/configuration_utils.py
neon_utils/message_utils.py
neon_utils/mq_utils.py
neon_utils/packaging_utils.py
neon_utils/skills/common_message_skill.py
neon_utils/skills/common_play_skill.py
neon_utils/skills/common_query_skill.py
neon_utils/skills/instructor_skill.py
neon_utils/skills/mycroft_skill.py
neon_utils/skills/neon_skill.py
neon_utils/user_utils.py
requirements/requirements.txt
tests/configuration_util_tests.py
tests/message_util_tests.py
tests/user_util_tests.py

Updates skill init to handle arbitrary args/kwargs
Updates neon skill init to move self params into properties

Refactor skill init and properties for latest ovos-workshop compat.

---

neon_utils/configuration_utils.py

Replace internal reference to `_safe_mycroft_config` with `Configuration`

Resolve internal reference to deprecated function

---

neon_utils/metrics_utils.py
neon_utils/skills/mycroft_skill.py
tests/metric_util_tests.py

Override `MycroftSkill._init_settings_manager` to resolve deprecated reference in ovos-core
Update core version reference in `metrics_utils` to remove deprecated reference

Resolve deprecation warnings

---

.github/workflows/publish_test_build.yml
requirements/requirements.txt

Update ovos-utils dependency to stable version
Implements a test branch of [.github](https://github.com/NeonGeckoCom/.github/pull/53) shared automation to test sdist action

Update dependencies and Test sdist publication

---

.github/workflows/publish_test_build.yml

Update GH Automation to default branch

---

neon_utils/configuration_utils.py
neon_utils/skills/neon_fallback_skill.py
neon_utils/skills/neon_skill.py
tests/user_util_tests.py

Updates config handling to resolve warning logs
Troubleshoot fallback skill init compat with ovos-workshop changes

Troubleshoot ovos-workshop compat.

---

neon_utils/configuration_utils.py
neon_utils/file_utils.py

Skip config init if defaults are configured via envvars
Update file_utils imports to prevent extra logged warnings

Update Config Handling

---

neon_utils/skills/mycroft_skill.py
neon_utils/skills/neon_fallback_skill.py
neon_utils/skills/skill_gui.py
neon_utils/validator_utils.py
requirements/requirements.txt

Deprecate SkillGUI override

---

.github/workflows/unit_tests.yml
neon_utils/skills/neon_fallback_skill.py

Update ovos_workshop import to resolve deprecation warning

Update deprecated import to expected path

---

neon_utils/language_utils.py
tests/language_util_tests.py

Fix logic in language support for translation and LF
Update language support unit test

Supported Languages bugfix and unit test

---

neon_utils/skills/mycroft_skill.py

Add `lang` to message.data for `speak` messages

Troubleshooting spoken responses in a non-default language

---

neon_utils/web_utils.py

Simplify logic and cleanup logging in web_utils

Update logging for better readability

---

.github/workflows/license_tests.yml
neon_utils/skills/common_query_skill.py
neon_utils/skills/mycroft_skill.py
neon_utils/skills/neon_skill.py
requirements/requirements.txt

Emits a `mycroft.skill.handler.complete` message after a CommonQuery skill action is completed
Back-port of https://github.com/OpenVoiceOS/OVOS-workshop/pull/142

Emit handler complete event for CommonQuery skills

---

neon_utils/skills/neon_skill.py
tests/neon_skill_tests.py

Add tests and methods to ensure backwards-compat in `NeonSkill`
Fixes https://github.com/NeonGeckoCom/neon-utils/pull/477

Skill Compatibility

---

neon_utils/signal_utils.py
neon_utils/skills/neon_skill.py

Catch and handle errors overriding signal methods

Better exception handling around signal method patching

---

neon_utils/metrics_utils.py
tests/metric_util_tests.py

Add an option to enable `Stopwatch` to report recorded metrics via the Messagebus

Implement stopwatch metrics reporting with unit test

---

neon_utils/location_utils.py
tests/location_util_tests.py

Annotate known public Nominatim servers
Update tests to avoid hitting rate limits
Workaround until #441 is completed
Test failures noted https://github.com/NeonGeckoCom/neon-utils/pull/487

Troubleshoot Location test failures

---

neon_utils/skills/neon_skill.py

Update `add_event` patching to work around FakeBus compat.

---

neon_utils/skills/mycroft_skill.py
neon_utils/skills/neon_fallback_skill.py
neon_utils/skills/neon_skill.py
tests/neon_skill_tests.py

Refactor NeonFallbackSkill for ovos-workshop compat
Mark NeonFallbackSkill as deprecated
Relates to https://github.com/NeonGeckoCom/NeonCore/pull/600

Refactor and Deprecate NeonFallbackSkill

---

.gitignore
neon_utils/packaging_utils.py
tests/packaging_util_tests.py

Adds a utility function for installing Pip packages
https://github.com/NeonGeckoCom/neon_enclosure/issues/84

feat: adds function for installing packages via pip

---

neon_utils/hana_utils.py
tests/hana_util_tests.py

Update Hana utils to use production server
Update Hana utils and tests to support multiple server configs

Update Hana utils to prep for release

---

requirements/requirements.txt

Loosen ovos-utils dependency to allow 0.1

---

neon_utils/metrics_utils.py
tests/metric_util_tests.py

Handle exceptions if stopwatch `stop` is called before `start`
Add unit test coverage for changes

Update stopwatch to include error handling with unit tests

---

neon_utils/location_utils.py
tests/location_util_tests.py

Update parsing to include 'hamlet' in Nominatim return as a kind of "city"
Closes #511

Treat 'hamlet' location as a 'city'

---

neon_utils/skills/common_query_skill.py

Update (deprecated) `CommonQuerySkill` implementation for compat with ovos-core 0.0.8
Fixes response bug missed in https://github.com/NeonGeckoCom/NeonCore/pull/641

Fix ovos-core 0.0.8 Common Query compat.

---

neon_utils/mq_utils.py
neon_utils/skills/neon_skill.py
tests/location_util_tests.py

Update overridden `send_email` method to send an email via HANA instead of a direct MQ call

Refactor to use HANA to send email instead of MQ

---

neon_utils/log_utils.py

Update `init_log` to use shared logic from `ovos_utils`
Update `level_overrides` config handling to support new config structure

Update `init_log` for better integration with `ovos-utils` and configuration changes

---

.github/workflows/unit_tests.yml
tests/mq_util_tests.py

Mark MQ Util tests as deprecated
remove GHA for MQ Util Tests

Skip tests for deprecated MQ utils module
